language: node_js

node_js:
  - "8"

env:
  - TEST_HOST=http://localhost:3000

cache:
  directories:
    - node_modules

install:
  - ./build install

before_script:
  - ./build offlinestart

script:
  - ./build test
