language: node_js

node_js:
  - "8"

env:
  - TEST_HOST=http://localhost:3000

cache:
  directories:
    - node_modules

install:
  - echo Installing source NPM dependencies...
  - npm install
  - echo
  - echo Installing Serverless...
  - npm install -g serverless@1.26.1
  - if ! serverless --version ; then exit 1; fi
  - serverless --version

before_script:
  - echo Start Serverless offline mode...
  - serverless offline start > /dev/null &  # run offline mode in background
  - sleep 10

script:
  - echo Running test...
  - npm test
