service: callingcode-restapi-lambda

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}  
  region: ap-southeast-1

functions:
  lookup-Get:
    handler: src/lookup.lookup
    events:
      - http:
         method: get
         path: callingcode/lookup
  list-Get:
    handler: src/list.list
    events:
      - http:
          method: get
          path: callingcode