service: callingcode-restapi-lambda

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}  
  region: ap-southeast-1

plugins:
  - serverless-offline

functions:
  lookup:
    handler: callingcode/lookup.lookup
    events:
      - http:
         method: get
         path: callingcode/lookup
  list:
    handler: callingcode/list.list
    events:
      - http:
          method: get
          path: callingcode
  get:
    handler: callingcode/get.get
    events:
      - http:
          method: get
          path: callingcode/{code}
